# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 821)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fs = QtWidgets.QLabel(self.centralwidget)
        self.fs.setGeometry(QtCore.QRect(50, 40, 140, 20))
        self.fs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs.setObjectName("fs")
        self.fs_display = QtWidgets.QLineEdit(self.centralwidget)
        self.fs_display.setGeometry(QtCore.QRect(50, 60, 100, 20))
        self.fs_display.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fs_display.setObjectName("fs_display")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(900, 710, 201, 51))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.logo.setObjectName("logo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 170, 200, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.fin = QtWidgets.QLabel(self.centralwidget)
        self.fin.setGeometry(QtCore.QRect(50, 80, 111, 21))
        self.fin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fin.setObjectName("fin")
        self.clk_option = QtWidgets.QLabel(self.centralwidget)
        self.clk_option.setGeometry(QtCore.QRect(30, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clk_option.setFont(font)
        self.clk_option.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clk_option.setObjectName("clk_option")
        self.clk_option_cfg_button = QtWidgets.QToolButton(self.centralwidget)
        self.clk_option_cfg_button.setGeometry(QtCore.QRect(150, 20, 37, 21))
        self.clk_option_cfg_button.setObjectName("clk_option_cfg_button")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 10, 200, 10))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(215, 15, 10, 160))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.fin_display = QtWidgets.QLineEdit(self.centralwidget)
        self.fin_display.setGeometry(QtCore.QRect(50, 100, 100, 21))
        self.fin_display.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fin_display.setObjectName("fin_display")
        self.fin_2 = QtWidgets.QLabel(self.centralwidget)
        self.fin_2.setGeometry(QtCore.QRect(50, 120, 111, 20))
        self.fin_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fin_2.setObjectName("fin_2")
        self.fin_display_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.fin_display_2.setGeometry(QtCore.QRect(50, 140, 101, 21))
        self.fin_display_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fin_display_2.setObjectName("fin_display_2")
        self.fs_2 = QtWidgets.QLabel(self.centralwidget)
        self.fs_2.setGeometry(QtCore.QRect(152, 60, 31, 20))
        self.fs_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_2.setObjectName("fs_2")
        self.fs_3 = QtWidgets.QLabel(self.centralwidget)
        self.fs_3.setGeometry(QtCore.QRect(152, 100, 31, 20))
        self.fs_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_3.setObjectName("fs_3")
        self.fs_4 = QtWidgets.QLabel(self.centralwidget)
        self.fs_4.setGeometry(QtCore.QRect(152, 140, 31, 20))
        self.fs_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_4.setObjectName("fs_4")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(15, 15, 10, 160))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(20, 205, 205, 10))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.DDC_CONFIG = QtWidgets.QLabel(self.centralwidget)
        self.DDC_CONFIG.setGeometry(QtCore.QRect(50, 215, 125, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DDC_CONFIG.setFont(font)
        self.DDC_CONFIG.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DDC_CONFIG.setObjectName("DDC_CONFIG")
        self.fs_5 = QtWidgets.QLabel(self.centralwidget)
        self.fs_5.setGeometry(QtCore.QRect(40, 245, 150, 20))
        self.fs_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_5.setObjectName("fs_5")
        self.chip_mode_config = QtWidgets.QComboBox(self.centralwidget)
        self.chip_mode_config.setGeometry(QtCore.QRect(30, 275, 180, 25))
        self.chip_mode_config.setObjectName("chip_mode_config")
        self.fs_6 = QtWidgets.QLabel(self.centralwidget)
        self.fs_6.setGeometry(QtCore.QRect(40, 305, 90, 20))
        self.fs_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_6.setObjectName("fs_6")
        self.real_mode_config = QtWidgets.QComboBox(self.centralwidget)
        self.real_mode_config.setGeometry(QtCore.QRect(30, 325, 90, 25))
        self.real_mode_config.setObjectName("real_mode_config")
        self.fs_7 = QtWidgets.QLabel(self.centralwidget)
        self.fs_7.setGeometry(QtCore.QRect(40, 405, 150, 20))
        self.fs_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_7.setObjectName("fs_7")
        self.ddc0_config = QtWidgets.QComboBox(self.centralwidget)
        self.ddc0_config.setGeometry(QtCore.QRect(30, 425, 180, 25))
        self.ddc0_config.setObjectName("ddc0_config")
        self.fs_8 = QtWidgets.QLabel(self.centralwidget)
        self.fs_8.setGeometry(QtCore.QRect(40, 455, 150, 20))
        self.fs_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_8.setObjectName("fs_8")
        self.ddc1_config = QtWidgets.QComboBox(self.centralwidget)
        self.ddc1_config.setGeometry(QtCore.QRect(30, 475, 180, 25))
        self.ddc1_config.setObjectName("ddc1_config")
        self.fs_9 = QtWidgets.QLabel(self.centralwidget)
        self.fs_9.setGeometry(QtCore.QRect(40, 505, 150, 20))
        self.fs_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_9.setObjectName("fs_9")
        self.ddc2_config = QtWidgets.QComboBox(self.centralwidget)
        self.ddc2_config.setGeometry(QtCore.QRect(30, 525, 180, 25))
        self.ddc2_config.setObjectName("ddc2_config")
        self.fs_10 = QtWidgets.QLabel(self.centralwidget)
        self.fs_10.setGeometry(QtCore.QRect(40, 555, 150, 20))
        self.fs_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_10.setObjectName("fs_10")
        self.ddc3_config = QtWidgets.QComboBox(self.centralwidget)
        self.ddc3_config.setGeometry(QtCore.QRect(30, 575, 180, 25))
        self.ddc3_config.setObjectName("ddc3_config")
        self.nco0_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.nco0_line_edit.setGeometry(QtCore.QRect(100, 610, 70, 20))
        self.nco0_line_edit.setObjectName("nco0_line_edit")
        self.fs_11 = QtWidgets.QLabel(self.centralwidget)
        self.fs_11.setGeometry(QtCore.QRect(30, 610, 70, 20))
        self.fs_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_11.setObjectName("fs_11")
        self.fs_12 = QtWidgets.QLabel(self.centralwidget)
        self.fs_12.setGeometry(QtCore.QRect(180, 610, 31, 20))
        self.fs_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_12.setObjectName("fs_12")
        self.nco1_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.nco1_line_edit.setGeometry(QtCore.QRect(100, 640, 70, 20))
        self.nco1_line_edit.setObjectName("nco1_line_edit")
        self.fs_13 = QtWidgets.QLabel(self.centralwidget)
        self.fs_13.setGeometry(QtCore.QRect(30, 640, 70, 20))
        self.fs_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_13.setObjectName("fs_13")
        self.fs_14 = QtWidgets.QLabel(self.centralwidget)
        self.fs_14.setGeometry(QtCore.QRect(180, 640, 31, 20))
        self.fs_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_14.setObjectName("fs_14")
        self.nco2_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.nco2_line_edit.setGeometry(QtCore.QRect(100, 670, 70, 20))
        self.nco2_line_edit.setObjectName("nco2_line_edit")
        self.fs_15 = QtWidgets.QLabel(self.centralwidget)
        self.fs_15.setGeometry(QtCore.QRect(30, 670, 70, 20))
        self.fs_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_15.setObjectName("fs_15")
        self.fs_16 = QtWidgets.QLabel(self.centralwidget)
        self.fs_16.setGeometry(QtCore.QRect(180, 670, 31, 20))
        self.fs_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_16.setObjectName("fs_16")
        self.nco3_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.nco3_line_edit.setGeometry(QtCore.QRect(100, 700, 70, 20))
        self.nco3_line_edit.setObjectName("nco3_line_edit")
        self.fs_17 = QtWidgets.QLabel(self.centralwidget)
        self.fs_17.setGeometry(QtCore.QRect(30, 700, 70, 20))
        self.fs_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_17.setObjectName("fs_17")
        self.fs_18 = QtWidgets.QLabel(self.centralwidget)
        self.fs_18.setGeometry(QtCore.QRect(180, 700, 31, 20))
        self.fs_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_18.setObjectName("fs_18")
        self.nco_update_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.nco_update_pushButton.setGeometry(QtCore.QRect(50, 730, 100, 23))
        self.nco_update_pushButton.setObjectName("nco_update_pushButton")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(20, 760, 205, 10))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(15, 210, 10, 555))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(220, 210, 10, 555))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.init_button = QtWidgets.QPushButton(self.centralwidget)
        self.init_button.setGeometry(QtCore.QRect(920, 20, 75, 41))
        self.init_button.setObjectName("init_button")
        self.mem_rd_button = QtWidgets.QPushButton(self.centralwidget)
        self.mem_rd_button.setGeometry(QtCore.QRect(1010, 20, 75, 41))
        self.mem_rd_button.setObjectName("mem_rd_button")
        self.DDC_CONFIG_2 = QtWidgets.QLabel(self.centralwidget)
        self.DDC_CONFIG_2.setGeometry(QtCore.QRect(940, 90, 130, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DDC_CONFIG_2.setFont(font)
        self.DDC_CONFIG_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DDC_CONFIG_2.setObjectName("DDC_CONFIG_2")
        self.fs_19 = QtWidgets.QLabel(self.centralwidget)
        self.fs_19.setGeometry(QtCore.QRect(950, 120, 20, 20))
        self.fs_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_19.setObjectName("fs_19")
        self.fs_20 = QtWidgets.QLabel(self.centralwidget)
        self.fs_20.setGeometry(QtCore.QRect(950, 145, 21, 20))
        self.fs_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_20.setObjectName("fs_20")
        self.fs_21 = QtWidgets.QLabel(self.centralwidget)
        self.fs_21.setGeometry(QtCore.QRect(950, 170, 21, 20))
        self.fs_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_21.setObjectName("fs_21")
        self.fs_22 = QtWidgets.QLabel(self.centralwidget)
        self.fs_22.setGeometry(QtCore.QRect(950, 195, 21, 20))
        self.fs_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_22.setObjectName("fs_22")
        self.fs_23 = QtWidgets.QLabel(self.centralwidget)
        self.fs_23.setGeometry(QtCore.QRect(950, 220, 21, 20))
        self.fs_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_23.setObjectName("fs_23")
        self.fs_24 = QtWidgets.QLabel(self.centralwidget)
        self.fs_24.setGeometry(QtCore.QRect(950, 245, 21, 20))
        self.fs_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_24.setObjectName("fs_24")
        self.fs_25 = QtWidgets.QLabel(self.centralwidget)
        self.fs_25.setGeometry(QtCore.QRect(950, 270, 21, 20))
        self.fs_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_25.setObjectName("fs_25")
        self.ntotal_reg_cfg = QtWidgets.QComboBox(self.centralwidget)
        self.ntotal_reg_cfg.setGeometry(QtCore.QRect(970, 120, 80, 20))
        self.ntotal_reg_cfg.setObjectName("ntotal_reg_cfg")
        self.m_reg_cfg = QtWidgets.QComboBox(self.centralwidget)
        self.m_reg_cfg.setGeometry(QtCore.QRect(970, 145, 80, 20))
        self.m_reg_cfg.setObjectName("m_reg_cfg")
        self.l_reg_cfg = QtWidgets.QComboBox(self.centralwidget)
        self.l_reg_cfg.setGeometry(QtCore.QRect(970, 170, 80, 20))
        self.l_reg_cfg.setObjectName("l_reg_cfg")
        self.f_reg_cfg = QtWidgets.QComboBox(self.centralwidget)
        self.f_reg_cfg.setGeometry(QtCore.QRect(970, 195, 80, 20))
        self.f_reg_cfg.setObjectName("f_reg_cfg")
        self.s_reg_cfg = QtWidgets.QComboBox(self.centralwidget)
        self.s_reg_cfg.setGeometry(QtCore.QRect(970, 220, 80, 20))
        self.s_reg_cfg.setObjectName("s_reg_cfg")
        self.k_reg_cfg = QtWidgets.QComboBox(self.centralwidget)
        self.k_reg_cfg.setGeometry(QtCore.QRect(970, 245, 80, 20))
        self.k_reg_cfg.setObjectName("k_reg_cfg")
        self.n_reg_cfg = QtWidgets.QComboBox(self.centralwidget)
        self.n_reg_cfg.setGeometry(QtCore.QRect(970, 270, 80, 20))
        self.n_reg_cfg.setObjectName("n_reg_cfg")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(920, 80, 160, 10))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(1075, 85, 10, 250))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(920, 330, 160, 10))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(915, 85, 10, 250))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.j204b_update_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.j204b_update_pushButton.setGeometry(QtCore.QRect(950, 300, 100, 23))
        self.j204b_update_pushButton.setObjectName("j204b_update_pushButton")
        self.DDC_CONFIG_3 = QtWidgets.QLabel(self.centralwidget)
        self.DDC_CONFIG_3.setGeometry(QtCore.QRect(950, 370, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DDC_CONFIG_3.setFont(font)
        self.DDC_CONFIG_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DDC_CONFIG_3.setObjectName("DDC_CONFIG_3")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(920, 360, 160, 10))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.cali_run_button = QtWidgets.QPushButton(self.centralwidget)
        self.cali_run_button.setGeometry(QtCore.QRect(964, 500, 64, 64))
        self.cali_run_button.setText("")
        self.cali_run_button.setObjectName("cali_run_button")
        self.cali_run_button.setStyleSheet("QPushButton{border-image: url(./ui_base/start.png)}")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(960, 440, 71, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(960, 420, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(960, 460, 71, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(960, 480, 71, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(960, 400, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(920, 570, 160, 10))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(1075, 365, 10, 340))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(915, 365, 10, 340))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.read_button = QtWidgets.QPushButton(self.centralwidget)
        self.read_button.setGeometry(QtCore.QRect(940, 590, 50, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.read_button.setFont(font)
        self.read_button.setObjectName("read_button")
        self.write_button = QtWidgets.QPushButton(self.centralwidget)
        self.write_button.setGeometry(QtCore.QRect(1010, 590, 50, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.write_button.setFont(font)
        self.write_button.setObjectName("write_button")
        self.addr_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.addr_textEdit.setGeometry(QtCore.QRect(990, 640, 80, 30))
        self.addr_textEdit.setObjectName("addr_textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(940, 640, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(940, 670, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(990, 670, 80, 30))
        self.textEdit.setObjectName("textEdit")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(920, 700, 160, 10))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.sds_button = QtWidgets.QPushButton(self.centralwidget)
        self.sds_button.setGeometry(QtCore.QRect(245, 140, 150, 30))
        self.sds_button.setObjectName("sds_button")
        self.clk_option_2 = QtWidgets.QLabel(self.centralwidget)
        self.clk_option_2.setGeometry(QtCore.QRect(250, 20, 120, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clk_option_2.setFont(font)
        self.clk_option_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clk_option_2.setObjectName("clk_option_2")
        self.refclk_div = QtWidgets.QLineEdit(self.centralwidget)
        self.refclk_div.setGeometry(QtCore.QRect(330, 50, 40, 20))
        self.refclk_div.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.refclk_div.setObjectName("refclk_div")
        self.fs_26 = QtWidgets.QLabel(self.centralwidget)
        self.fs_26.setGeometry(QtCore.QRect(250, 50, 80, 20))
        self.fs_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_26.setObjectName("fs_26")
        self.fs_27 = QtWidgets.QLabel(self.centralwidget)
        self.fs_27.setGeometry(QtCore.QRect(250, 75, 61, 20))
        self.fs_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_27.setObjectName("fs_27")
        self.fbc_div = QtWidgets.QLineEdit(self.centralwidget)
        self.fbc_div.setGeometry(QtCore.QRect(330, 75, 40, 20))
        self.fbc_div.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fbc_div.setObjectName("fbc_div")
        self.fs_28 = QtWidgets.QLabel(self.centralwidget)
        self.fs_28.setGeometry(QtCore.QRect(250, 100, 61, 20))
        self.fs_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_28.setObjectName("fs_28")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(300, 100, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(395, 15, 10, 245))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(235, 15, 10, 245))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(240, 10, 160, 10))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(240, 255, 160, 10))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.sds_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.sds_button_2.setGeometry(QtCore.QRect(245, 180, 150, 30))
        self.sds_button_2.setObjectName("sds_button_2")
        self.sds_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.sds_button_3.setGeometry(QtCore.QRect(245, 220, 150, 30))
        self.sds_button_3.setObjectName("sds_button_3")
        self.mix_mode_config = QtWidgets.QComboBox(self.centralwidget)
        self.mix_mode_config.setGeometry(QtCore.QRect(130, 325, 90, 25))
        self.mix_mode_config.setObjectName("mix_mode_config")
        self.fs_29 = QtWidgets.QLabel(self.centralwidget)
        self.fs_29.setGeometry(QtCore.QRect(150, 305, 70, 20))
        self.fs_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_29.setObjectName("fs_29")
        self.fs_30 = QtWidgets.QLabel(self.centralwidget)
        self.fs_30.setGeometry(QtCore.QRect(40, 350, 80, 20))
        self.fs_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_30.setObjectName("fs_30")
        self.fs_31 = QtWidgets.QLabel(self.centralwidget)
        self.fs_31.setGeometry(QtCore.QRect(150, 350, 70, 20))
        self.fs_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_31.setObjectName("fs_31")
        self.freq_mode_config = QtWidgets.QComboBox(self.centralwidget)
        self.freq_mode_config.setGeometry(QtCore.QRect(30, 370, 90, 25))
        self.freq_mode_config.setObjectName("freq_mode_config")
        self.gain_mode_config = QtWidgets.QComboBox(self.centralwidget)
        self.gain_mode_config.setGeometry(QtCore.QRect(130, 370, 90, 25))
        self.gain_mode_config.setObjectName("gain_mode_config")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(440, 730, 70, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 730, 60, 20))
        self.label_3.setObjectName("label_3")
        self.fs_32 = QtWidgets.QLabel(self.centralwidget)
        self.fs_32.setGeometry(QtCore.QRect(515, 730, 30, 20))
        self.fs_32.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fs_32.setObjectName("fs_32")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 730, 75, 20))
        self.pushButton.setObjectName("pushButton")
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(280, 755, 580, 10))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.DDC_CONFIG_4 = QtWidgets.QLabel(self.centralwidget)
        self.DDC_CONFIG_4.setGeometry(QtCore.QRect(280, 730, 80, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DDC_CONFIG_4.setFont(font)
        self.DDC_CONFIG_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DDC_CONFIG_4.setObjectName("DDC_CONFIG_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(545, 730, 65, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 730, 30, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(740, 730, 40, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(790, 730, 30, 20))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/status/OFF.png"))
        self.label_6.setObjectName("label_6")
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(280, 715, 580, 10))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.centralwidget)
        self.line_24.setGeometry(QtCore.QRect(275, 720, 10, 40))
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(855, 720, 10, 40))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(230, 270, 681, 431))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/struc/structure.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 20, 501, 241))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/xxx/xxxx.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TR9XXX"))
        self.fs.setText(_translate("MainWindow", "ADC Sampling Rate"))
        self.fin.setText(_translate("MainWindow", "ADC input Freq"))
        self.clk_option.setText(_translate("MainWindow", "CLK OPT"))
        self.clk_option_cfg_button.setText(_translate("MainWindow", "..."))
        self.fin_2.setText(_translate("MainWindow", "Lane rate"))
        self.fs_2.setText(_translate("MainWindow", "MHz"))
        self.fs_3.setText(_translate("MainWindow", "MHz"))
        self.fs_4.setText(_translate("MainWindow", "GHz"))
        self.DDC_CONFIG.setText(_translate("MainWindow", "DDC CONFIG"))
        self.fs_5.setText(_translate("MainWindow", "Chip Operating Mode"))
        self.fs_6.setText(_translate("MainWindow", "output_mode"))
        self.fs_7.setText(_translate("MainWindow", "DDC0 Configuration"))
        self.fs_8.setText(_translate("MainWindow", "DDC1 Configuration"))
        self.fs_9.setText(_translate("MainWindow", "DDC2 Configuration"))
        self.fs_10.setText(_translate("MainWindow", "DDC3 Configuration"))
        self.fs_11.setText(_translate("MainWindow", "DDC0 NCO"))
        self.fs_12.setText(_translate("MainWindow", "MHz"))
        self.fs_13.setText(_translate("MainWindow", "DDC1 NCO"))
        self.fs_14.setText(_translate("MainWindow", "MHz"))
        self.fs_15.setText(_translate("MainWindow", "DDC2 NCO"))
        self.fs_16.setText(_translate("MainWindow", "MHz"))
        self.fs_17.setText(_translate("MainWindow", "DDC3 NCO"))
        self.fs_18.setText(_translate("MainWindow", "MHz"))
        self.nco_update_pushButton.setText(_translate("MainWindow", "NCO update"))
        self.init_button.setText(_translate("MainWindow", "Init"))
        self.mem_rd_button.setText(_translate("MainWindow", "MEM_RD"))
        self.DDC_CONFIG_2.setText(_translate("MainWindow", "204B CONFIG"))
        self.fs_19.setText(_translate("MainWindow", "N\'"))
        self.fs_20.setText(_translate("MainWindow", "M"))
        self.fs_21.setText(_translate("MainWindow", "L"))
        self.fs_22.setText(_translate("MainWindow", "F"))
        self.fs_23.setText(_translate("MainWindow", "S"))
        self.fs_24.setText(_translate("MainWindow", "K"))
        self.fs_25.setText(_translate("MainWindow", "N"))
        self.j204b_update_pushButton.setText(_translate("MainWindow", "204B update"))
        self.DDC_CONFIG_3.setText(_translate("MainWindow", "CALI RUN"))
        self.checkBox_3.setText(_translate("MainWindow", "cali2"))
        self.checkBox_2.setText(_translate("MainWindow", "cali1"))
        self.checkBox_4.setText(_translate("MainWindow", "cali3"))
        self.checkBox_5.setText(_translate("MainWindow", "cali4"))
        self.checkBox.setText(_translate("MainWindow", "cali0"))
        self.read_button.setText(_translate("MainWindow", "READ"))
        self.write_button.setText(_translate("MainWindow", "WRITE"))
        self.label_2.setText(_translate("MainWindow", "addr"))
        self.label.setText(_translate("MainWindow", "data"))
        self.sds_button.setText(_translate("MainWindow", "SDS update"))
        self.clk_option_2.setText(_translate("MainWindow", "SDS CONFIG"))
        self.fs_26.setText(_translate("MainWindow", "refclk_div"))
        self.fs_27.setText(_translate("MainWindow", "FBC div"))
        self.fs_28.setText(_translate("MainWindow", "FFE"))
        self.sds_button_2.setText(_translate("MainWindow", "test pattern PRBS7"))
        self.sds_button_3.setText(_translate("MainWindow", "test pattern clk0101"))
        self.fs_29.setText(_translate("MainWindow", "mix_mode"))
        self.fs_30.setText(_translate("MainWindow", "freq_mode"))
        self.fs_31.setText(_translate("MainWindow", "gain_mode"))
        self.label_3.setText(_translate("MainWindow", "SPI_CLK"))
        self.fs_32.setText(_translate("MainWindow", "MHz"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.DDC_CONFIG_4.setText(_translate("MainWindow", "SPI_CFG"))
        self.label_4.setText(_translate("MainWindow", "TranBits"))
        self.label_5.setText(_translate("MainWindow", "STATUS"))

from ui_base import logo_rc
from ui_base import status_rc
from ui_base import struc_rc
from ui_base import xxx_rc
